//! Fixed wire and adversarial evidence cases for the bounded workflow slice.
//! CRC vectors are independently calculated, not generated by the decoder under test.
use pcap_evidence::{
    correlate,
    dnp3::{self, Dnp3Result},
    engine::{ApplicationAnalysis, ApplicationData},
    provenance::{EvidenceBytes, PacketId},
    semantics::{self, dnp3_workflow as workflow, Limits as SemanticLimits, Status, Value},
    tcp::{StreamChunk, StreamResult},
    ErrorCode, Limits,
};

const VECTORS: &str = include_str!("fixtures/dnp3_workflows.hex");
fn wire(name: &str) -> Vec<u8> {
    let line = VECTORS
        .lines()
        .find(|line| line.split_whitespace().next() == Some(name))
        .unwrap();
    let text = line.split_whitespace().nth(1).unwrap();
    (0..text.len())
        .step_by(2)
        .map(|p| u8::from_str_radix(&text[p..p + 2], 16).unwrap())
        .collect()
}
fn evidence(bytes: &[u8], frame: u64) -> EvidenceBytes {
    EvidenceBytes::from_packet(
        bytes,
        PacketId {
            capture: [7; 32],
            frame,
            record_offset: frame * 100,
        },
        54,
    )
}
fn stream(parts: &[Vec<u8>]) -> StreamResult {
    let mut all = EvidenceBytes::default();
    for (i, bytes) in parts.iter().enumerate() {
        all.append(&evidence(bytes, i as u64 + 1), 1024 * 1024)
            .unwrap();
    }
    StreamResult {
        base_sequence: Some(1000),
        anchored_by_syn: true,
        chunks: vec![StreamChunk {
            offset: 0,
            bytes: all,
        }],
        gaps: Vec::new(),
        conflicts: Vec::new(),
        duplicate_observed_bytes: 0,
    }
}
fn decode(names: &[&str]) -> Dnp3Result {
    let parts: Vec<_> = names.iter().map(|n| wire(n)).collect();
    dnp3::decode(&stream(&parts), &Limits::default()).unwrap()
}
fn application(names: &[&str], direction: usize) -> ApplicationAnalysis {
    ApplicationAnalysis {
        flow: 0,
        direction,
        protocol: "dnp3",
        data: ApplicationData::Dnp3(decode(names)),
    }
}
fn apdu(name: &str) -> EvidenceBytes {
    decode(&[name]).fragments[0].raw.clone()
}
fn status(bytes: &[u8]) -> Status {
    workflow::application(&evidence(bytes, 1), SemanticLimits::default())
        .unwrap()
        .status()
}
// Polynomial orientation differs from production's reflected shift register.
fn independent_crc(bytes: &[u8]) -> u16 {
    let mut r = 0u16;
    for b in bytes {
        r ^= u16::from(b.reverse_bits()) << 8;
        for _ in 0..8 {
            r = (r << 1) ^ if r & 0x8000 != 0 { 0x3d65 } else { 0 };
        }
    }
    r.reverse_bits() ^ 0xffff
}
fn reheader(mut frame: Vec<u8>, control: u8) -> Vec<u8> {
    frame[3] = control;
    let crc = independent_crc(&frame[..8]).to_le_bytes();
    frame[8..10].copy_from_slice(&crc);
    frame
}

#[test]
fn fixed_vectors_have_independent_crc_and_exact_frame_extent() {
    assert_eq!(independent_crc(b"123456789"), 0xea82);
    for name in [
        "confirm_solicited",
        "confirm_unsolicited",
        "class_scan_15",
        "unsolicited_event",
        "delay_measure",
        "delay_response",
        "record_time",
        "time_write_absolute",
        "time_write_recorded",
        "enable_classes",
        "disable_classes",
    ] {
        let bytes = wire(name);
        let source = evidence(&bytes, 1);
        let (frame, used) = dnp3::parse_link(&source, 0, 0).unwrap();
        assert_eq!(used, bytes.len(), "{name}");
        assert_eq!(frame.raw, source);
        assert_eq!(independent_crc(&bytes[..8]).to_le_bytes(), bytes[8..10]);
        assert!(frame.user_data.validate());
    }
}

#[test]
fn all_control_bytes_preserve_raw_primary_secondary_masks() {
    for raw in 0..=255u8 {
        let c = dnp3::link_control(raw);
        assert_eq!(c.direction, raw & 128 != 0);
        assert_eq!(c.primary, raw & 64 != 0);
        assert_eq!(c.function, raw & 15);
        if c.primary {
            assert_eq!(c.fcb, Some(raw & 32 != 0));
            assert_eq!(c.fcv, Some(raw & 16 != 0));
            assert_eq!(c.dfc, None);
            assert_eq!(c.reserved, None);
        } else {
            assert_eq!(c.fcb, None);
            assert_eq!(c.fcv, None);
            assert_eq!(c.dfc, Some(raw & 16 != 0));
            assert_eq!(c.reserved, Some(raw & 32 != 0));
        }
    }
}

#[test]
fn link_subset_reports_reserved_unsupported_and_invalid_combinations() {
    for (name, expected) in [
        ("secondary_dfc", Status::DecodedSubset),
        ("test_link_valid", Status::DecodedSubset),
        ("secondary_reserved", Status::Rejected),
        ("primary_reserved", Status::Unsupported),
        ("legacy_primary", Status::Unsupported),
        ("test_link_bad_fcv", Status::Rejected),
        ("user_data_bad_fcv", Status::Rejected),
        ("secondary_with_user_data", Status::Rejected),
        ("reserved_destination", Status::Rejected),
        ("self_destination", Status::Unsupported),
        ("broadcast_wrong_direction", Status::Rejected),
    ] {
        let source = evidence(&wire(name), 1);
        let report = workflow::link(&source, SemanticLimits::default()).unwrap();
        assert_eq!(report.status(), expected, "{name}");
        let parsed = dnp3::decode(&stream(&[wire(name)]), &Limits::default()).unwrap();
        assert_eq!(parsed.frames.len(), 1, "raw link evidence must remain");
        assert!(parsed.messages.is_empty());
    }
}

#[test]
fn fcb_is_retained_but_not_used_as_endpoint_state_when_fcv_is_zero() {
    for control in [0xc4, 0xe4] {
        let bytes = reheader(wire("record_time"), control);
        let parsed = dnp3::decode(&stream(&[bytes]), &Limits::default()).unwrap();
        assert_eq!(parsed.messages.len(), 1);
        assert!(parsed.issues.is_empty());
    }
}

#[test]
fn all_broadcast_addresses_are_explicit_and_not_pairable() {
    for (name, address, policy) in [
        ("broadcast_fffd", 0xfffd, "not_required"),
        ("broadcast_fffe", 0xfffe, "required"),
        ("broadcast_ffff", 0xffff, "optional"),
    ] {
        let d = decode(&[name]);
        assert!(d.frames[0].broadcast);
        assert_eq!(d.frames[0].destination, address);
        assert_eq!(workflow::broadcast_confirm_policy(address), Some(policy));
        assert_eq!(workflow::address_kind(address), "broadcast");
        let transactions =
            correlate::transactions(&[application(&[name], 0)], &Limits::default()).unwrap();
        assert_eq!(transactions[0].status, "unclassified");
        assert_eq!(
            transactions[0].reason,
            "dnp3_pairing_non_individual_address"
        );
    }
    assert_eq!(workflow::address_kind(0xffef), "individual");
    assert_eq!(workflow::address_kind(0xfff0), "reserved");
    assert_eq!(workflow::address_kind(0xfffc), "self_address");
}

#[test]
fn link_fields_have_exact_control_and_address_witnesses() {
    let source = evidence(&wire("secondary_dfc"), 7);
    let r = workflow::link(&source, SemanticLimits::default()).unwrap();
    let fields = r.records()[0].fields();
    assert_eq!(
        fields.iter().find(|f| f.name() == "dfc").unwrap().range(),
        3..4
    );
    assert_eq!(
        fields.iter().find(|f| f.name() == "dfc").unwrap().bit(),
        Some(4)
    );
    assert_eq!(
        fields
            .iter()
            .find(|f| f.name() == "source")
            .unwrap()
            .range(),
        6..8
    );
    let json = r.json().unwrap().encode();
    assert!(json.contains("\"frame\":\"7\""));
    assert!(json.contains("\"packet_start\":\"57\""));
    assert!(json.contains("\"device_effect_established\":false"));
}

#[test]
fn confirms_and_unsolicited_namespace_are_byte_derived() {
    for name in ["confirm_solicited", "confirm_unsolicited"] {
        let raw = apdu(name);
        let r = workflow::application(&raw, SemanticLimits::default()).unwrap();
        assert_eq!(r.status(), Status::DecodedSubset);
        assert!(r.records().iter().any(|r| r.kind() == "confirm"));
        assert_eq!(r.consumed(), 2);
    }
    assert!(workflow::header(&apdu("confirm_unsolicited"))
        .unwrap()
        .unsolicited());
    assert!(!workflow::header(&apdu("confirm_solicited"))
        .unwrap()
        .unsolicited());
    for invalid in [&[0xe3, 0][..], &[0xc3, 0, 0][..], &[0x83, 0][..]] {
        assert_eq!(status(invalid), Status::Rejected);
    }
    let raw = apdu("unsolicited_event");
    let r = workflow::application(&raw, SemanticLimits::default()).unwrap();
    assert_eq!(r.status(), Status::DecodedSubset);
    assert!(r
        .records()
        .iter()
        .any(|r| r.kind() == "unsolicited_response"));
    assert_eq!(status(&[0xc3, 0x82, 0, 0]), Status::Rejected);
    assert_eq!(status(&[0xd3, 0x81, 0, 0]), Status::Rejected);
}

#[test]
fn class_event_scans_and_index_selectors_reuse_the_root_parser() {
    let raw = apdu("class_scan_15");
    let r = workflow::application(&raw, SemanticLimits::default()).unwrap();
    let classes: Vec<_> = r
        .records()
        .iter()
        .filter(|r| r.kind() == "class_selector")
        .collect();
    assert_eq!(classes.len(), 4);
    for (i, record) in classes.iter().enumerate() {
        let class = record
            .fields()
            .iter()
            .find(|f| f.name() == "class")
            .unwrap();
        assert_eq!(class.value(), &Value::Unsigned(i as u64));
        assert_eq!(class.range(), 3 + i * 3..4 + i * 3);
    }
    assert_eq!(r.status(), Status::DecodedSubset);
    let raw = evidence(&[0xc1, 1, 2, 0, 0x17, 2, 7, 9], 1);
    let r = workflow::application(&raw, SemanticLimits::default()).unwrap();
    assert_eq!(r.status(), Status::DecodedSubset);
    assert_eq!(
        r.records()
            .iter()
            .filter(|r| r.kind() == "read_point_selector")
            .count(),
        2
    );
    assert!(r.records().iter().all(|r| r.kind() != "object_value"));
    assert!(r
        .records()
        .iter()
        .any(|r| r.kind() == "event_object_header"));
}

#[test]
fn class_controls_are_bounded_selectors_not_inferred_configuration() {
    for name in ["enable_classes", "disable_classes"] {
        let raw = apdu(name);
        let r = workflow::application(&raw, SemanticLimits::default()).unwrap();
        assert_eq!(r.status(), Status::DecodedSubset);
        assert!(r.records().iter().all(|r| r.kind() != "object_value"));
    }
    assert_eq!(status(&[0xc0, 20]), Status::Rejected);
    assert_eq!(status(&[0xc0, 20, 60, 1, 6]), Status::Unsupported);
    assert_eq!(status(&[0xc0, 20, 60, 2, 7, 0]), Status::Unsupported);
    assert_eq!(status(&[0xc0, 21, 60, 2, 0, 0, 0]), Status::Unsupported);
    // READ keeps the pre-existing zero count / one, two, four byte range contract.
    for selector in [
        vec![2, 0, 7, 0],
        vec![2, 0, 0, 0, 0],
        vec![2, 0, 1, 0, 0, 0, 0],
        vec![2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
    ] {
        let mut b = vec![0xc0, 1];
        b.extend(selector);
        assert_eq!(status(&b), Status::DecodedSubset);
    }
}

#[test]
fn non_secure_time_workflows_preserve_raw_time_and_exact_spans() {
    for name in [
        "delay_measure",
        "record_time",
        "delay_response",
        "time_write_absolute",
        "time_write_recorded",
    ] {
        let raw = apdu(name);
        let r = workflow::application(&raw, SemanticLimits::default()).unwrap();
        assert_eq!(r.status(), Status::DecodedSubset, "{name}");
        assert_eq!(r.consumed(), raw.len());
    }
    let raw = apdu("time_write_absolute");
    let r = workflow::application(&raw, SemanticLimits::default()).unwrap();
    let object = r
        .records()
        .iter()
        .find(|r| r.kind() == "object_value")
        .unwrap();
    assert_eq!(object.range(), 6..12);
    assert!(object
        .fields()
        .iter()
        .any(|f| f.value() == &Value::Milliseconds48(123456)));
    assert_eq!(status(&[0xc0, 23, 0]), Status::Rejected);
    assert_eq!(status(&[0xc0, 24, 0]), Status::Rejected);
    assert_eq!(status(&[0xc0, 2, 50, 1, 7, 0]), Status::Unsupported);
    assert_eq!(status(&[0xc0, 2, 50, 1, 7, 2]), Status::Unsupported);
    assert_eq!(status(&[0xc0, 2, 50, 1, 0, 0, 0]), Status::Unsupported);
    assert_eq!(status(&[0xc0, 2, 50, 2, 7, 1]), Status::Unsupported);
}

#[test]
fn secure_file_authentication_and_unreviewed_families_remain_opaque() {
    for name in ["secure_auth_request", "file_auth_request"] {
        let raw = apdu(name);
        let r = workflow::application(&raw, SemanticLimits::default()).unwrap();
        assert_eq!(r.status(), Status::Unsupported);
        assert!(r.records().is_empty());
    }
    assert_eq!(status(&[0xc0, 1, 0, 254, 6]), Status::Unsupported);
    assert_eq!(status(&[0xc0, 0x81, 0, 0, 120, 1, 6]), Status::Unsupported);
}

#[test]
fn file_control_request_reaches_bounded_group70_projection() {
    let mut raw = vec![0xc0, 25, 70, 3, 0x5b, 1, 29, 0];
    raw.extend_from_slice(&[
        26, 0, 3, 0, 1, 2, 3, 4, 5, 6, 0x34, 0x12, 0xaa, 0xbb, 0xcc, 0xdd, 100, 0, 0, 0, 1, 0, 64,
        0, 9, 0, b'A', b'B', b'C',
    ]);
    let source = evidence(&raw, 1);
    let report = workflow::application(&source, SemanticLimits::default()).unwrap();
    assert_eq!(report.status(), Status::DecodedSubset);
    assert!(report.records().iter().any(|r| r.kind() == "file_control"));
    assert!(report.records().iter().any(|r| r.kind() == "file_object"));
}

#[test]
fn request_response_pairs_require_addresses_sequence_function_and_directions() {
    let a = [
        application(&["class_scan_15", "delay_measure"], 0),
        application(&["event_response_15", "delay_response"], 1),
    ];
    let t = correlate::transactions(&a, &Limits::default()).unwrap();
    assert_eq!(t.len(), 2);
    assert!(t.iter().all(|t| t.status == "candidate_pair"));
    let same_direction = [
        application(&["class_scan_15"], 0),
        application(&["event_response_15"], 0),
    ];
    let t = correlate::transactions(&same_direction, &Limits::default()).unwrap();
    assert_eq!(t[0].status, "ambiguous");
    assert_eq!(
        t[0].reason,
        "dnp3_request_response_capture_directions_not_opposite"
    );
}

#[test]
fn multiple_outstations_do_not_share_sequence_namespaces() {
    let a = [
        application(&["class_scan_15", "class_scan_outstation11"], 0),
        application(&["event_response_15", "empty_response_outstation11"], 1),
    ];
    let t = correlate::transactions(&a, &Limits::default()).unwrap();
    assert_eq!(t.len(), 2);
    assert!(t.iter().all(|t| t.status == "candidate_pair"));
}

#[test]
fn sequence_rollover_is_valid_but_reuse_stays_ambiguous() {
    let a = [
        application(&["class_scan_15", "event_scan_0"], 0),
        application(&["event_response_15", "empty_response_0"], 1),
    ];
    let t = correlate::transactions(&a, &Limits::default()).unwrap();
    assert_eq!(t.iter().filter(|t| t.status == "candidate_pair").count(), 2);
    let a = [
        application(&["class_scan_15", "event_scan_0", "class_scan_15"], 0),
        application(&["event_response_15", "empty_response_0"], 1),
    ];
    let t = correlate::transactions(&a, &Limits::default()).unwrap();
    assert_eq!(t.iter().filter(|t| t.status == "candidate_pair").count(), 1);
    assert_eq!(t.iter().filter(|t| t.status == "ambiguous").count(), 1);
}

#[test]
fn unmatched_no_response_confirm_and_unsolicited_are_not_fabricated_pairs() {
    for (name, direction, expected) in [
        ("class_scan_15", 0, "unanswered"),
        ("event_response_15", 1, "orphan_response"),
        ("no_response_control", 0, "no_response_expected"),
        ("confirm_unsolicited", 0, "confirmation"),
        ("unsolicited_event", 1, "unsolicited"),
    ] {
        let t = correlate::transactions(&[application(&[name], direction)], &Limits::default())
            .unwrap();
        assert_eq!(t.len(), 1);
        assert_eq!(t[0].status, expected, "{name}");
    }
}

#[test]
fn forged_metadata_or_link_direction_cannot_authorize_pairing() {
    let mut request = application(&["class_scan_15"], 0);
    if let ApplicationData::Dnp3(d) = &mut request.data {
        d.messages[0].first_sequence = 7;
    }
    let t = correlate::transactions(
        &[request, application(&["event_response_15"], 1)],
        &Limits::default(),
    )
    .unwrap();
    assert!(t.iter().all(|t| t.status != "candidate_pair"));
    let wrong_wire = reheader(wire("event_response_15"), 0xc4);
    let response = ApplicationAnalysis {
        flow: 0,
        direction: 1,
        protocol: "dnp3",
        data: ApplicationData::Dnp3(
            dnp3::decode(&stream(&[wrong_wire]), &Limits::default()).unwrap(),
        ),
    };
    let t = correlate::transactions(
        &[application(&["class_scan_15"], 0), response],
        &Limits::default(),
    )
    .unwrap();
    assert!(t.iter().all(|t| t.status != "candidate_pair"));
}

#[test]
fn cross_application_fragment_object_completion_has_exact_two_packet_spans() {
    let d = decode(&["application_first", "application_final"]);
    assert_eq!(d.messages.len(), 1);
    let m = &d.messages[0];
    assert!(m.complete);
    assert_eq!(m.objects.data(), &[2, 1, 0x17, 1, 7, 0x81]);
    assert_eq!(m.objects.spans().len(), 2);
    assert_eq!(m.objects.spans()[0].packet.frame, 1);
    assert_eq!(m.objects.spans()[0].start, 0);
    assert_eq!(m.objects.spans()[0].end, 5);
    assert_eq!(m.objects.spans()[0].packet_start, 69);
    assert_eq!(m.objects.spans()[1].packet.frame, 2);
    assert_eq!(m.objects.spans()[1].start, 5);
    assert_eq!(m.objects.spans()[1].end, 6);
    assert_eq!(m.objects.spans()[1].packet_start, 69);
    let r = semantics::dnp3::decode(
        &m.objects,
        semantics::dnp3::Context::ResponseValues,
        SemanticLimits::default(),
    )
    .unwrap();
    assert_eq!(r.status(), Status::DecodedSubset);
    assert_eq!(
        r.records()
            .iter()
            .find(|r| r.kind() == "object_value")
            .unwrap()
            .range(),
        4..6
    );
    for fragment in &d.fragments {
        let text = semantics::dnp3::fragment_json(fragment, SemanticLimits::default()).encode();
        assert!(text.contains("\"status\":\"incomplete\""));
        assert!(!text.contains("\"kind\":\"object_value\""));
    }
}

#[test]
fn missing_middle_or_first_never_decodes_partial_objects_as_a_complete_message() {
    let d = decode(&["application_first", "application_skipped_final"]);
    assert!(d.messages.iter().all(|m| !m.complete));
    for m in &d.messages {
        let text = semantics::dnp3::assembled_message_json(
            &m.objects,
            m.function,
            m.complete,
            SemanticLimits::default(),
        )
        .encode();
        assert!(text.contains("\"status\":\"incomplete\""));
        assert!(!text.contains("\"kind\":\"object_value\""));
    }
    assert!(decode(&["application_final"]).messages.is_empty());
    let d = decode(&["transport_first", "transport_final"]);
    assert!(d.messages.is_empty());
    assert!(d
        .issues
        .iter()
        .any(|i| i.code == "dnp3_transport_sequence_gap_or_conflict"));
}

#[test]
fn reordered_transport_duplicates_keep_all_witnesses_but_only_one_byte_value() {
    let d = decode(&[
        "transport_first",
        "transport_middle",
        "transport_first",
        "transport_final",
    ]);
    assert_eq!(d.messages.len(), 1);
    assert!(d.messages[0].complete);
    assert_eq!(d.messages[0].objects.data(), &[2, 1, 0x17, 1, 7, 0x81]);
    assert_eq!(d.messages[0].packets.len(), 4);
    assert_eq!(d.fragments[0].frames, vec![0, 1, 2, 3]);
    assert!(d
        .issues
        .iter()
        .any(|i| i.code == "reordered_duplicate_dnp3_transport_segment"));
    assert!(
        !workflow::verified_message_direction(&d, &d.messages[0], &Limits::default(), &mut 0)
            .unwrap()
    );
}

#[test]
fn conflicting_duplicates_and_late_continuations_never_majority_vote() {
    let d = decode(&[
        "transport_first",
        "transport_middle",
        "transport_middle_conflict",
        "transport_middle",
        "transport_final",
    ]);
    assert!(d.messages.is_empty());
    assert!(d
        .issues
        .iter()
        .any(|i| i.code == "conflicting_dnp3_transport_duplicate"));
    assert!(d
        .issues
        .iter()
        .any(|i| i.code == "orphan_dnp3_transport_segment"));
    assert_eq!(d.frames.len(), 5);
}

#[test]
fn declared_crc_failure_is_not_a_license_to_scan_nested_frames() {
    let outer = wire("bad_crc_nested_frame");
    let d = dnp3::decode(
        &stream(&[outer.clone(), wire("record_time")]),
        &Limits::default(),
    )
    .unwrap();
    assert_eq!(d.frames.len(), 1);
    assert_eq!(d.messages.len(), 1);
    assert_eq!(d.messages[0].function, 24);
    assert_eq!(d.rejected_link_ranges.len(), 1);
    let rejected = &d.rejected_link_ranges[0];
    assert_eq!(rejected.raw.data(), outer);
    assert_eq!(rejected.declared_length, Some(outer.len()));
    assert!(!rejected.incomplete);
    assert_eq!(rejected.raw.spans()[0].packet_start, 54);
}

#[test]
fn contradictory_length_and_bad_header_crc_do_not_silently_resynchronize() {
    let parts = [wire("declared_truncated"), wire("record_time")];
    let d = dnp3::decode(&stream(&parts), &Limits::default()).unwrap();
    assert!(d.messages.is_empty());
    assert_eq!(d.rejected_link_ranges.len(), 1);
    let r = &d.rejected_link_ranges[0];
    assert!(r.incomplete);
    assert_eq!(r.declared_length, Some(95)); // 10 + 75 data + ten block CRC bytes
    assert_eq!(r.raw.len(), parts[0].len() + parts[1].len());
    let mut bad = wire("confirm_solicited");
    bad[8] ^= 1;
    let d = dnp3::decode(&stream(&[bad, wire("record_time")]), &Limits::default()).unwrap();
    assert!(d.messages.is_empty());
    assert_eq!(d.rejected_link_ranges[0].declared_length, None);
}

#[test]
fn truncation_and_limits_remain_explicit_not_success() {
    let bytes = wire("time_write_absolute");
    for n in 0..bytes.len() {
        assert!(
            dnp3::parse_link(&evidence(&bytes[..n], 1), 0, 0).is_err(),
            "prefix {n}"
        );
    }
    let raw = apdu("time_write_absolute");
    let tiny = SemanticLimits {
        max_fields: 1,
        ..SemanticLimits::default()
    };
    assert_eq!(
        workflow::application(&raw, tiny).unwrap().status(),
        Status::Limited
    );
    let limits = Limits {
        max_correlation_checks: 1,
        ..Limits::default()
    };
    assert_eq!(
        correlate::transactions(&[application(&["class_scan_15"], 0)], &limits)
            .unwrap_err()
            .code,
        ErrorCode::LimitExceeded
    );
    let limits = Limits {
        max_application_bytes: 1,
        ..Limits::default()
    };
    assert_eq!(
        dnp3::decode(&stream(&[wire("bad_crc_nested_frame")]), &limits)
            .unwrap_err()
            .code,
        ErrorCode::LimitExceeded
    );
}

#[test]
fn workflow_json_is_deterministic_and_does_not_infer_time_or_effects() {
    let raw = apdu("time_write_recorded");
    let a = workflow::application(&raw, SemanticLimits::default())
        .unwrap()
        .json()
        .unwrap();
    let b = workflow::application(&raw, SemanticLimits::default())
        .unwrap()
        .json()
        .unwrap();
    assert_eq!(a, b);
    let text = a.encode();
    assert!(text.contains("\"normative_conformance_certified\":false"));
    assert!(text.contains("\"device_effect_established\":false"));
    assert!(!text.contains("latency_ms"));
}
