import {STATES,count,timestamp,virtualRange,shortValue,packetRefs,bytes,overlaps} from '/model.mjs';
const $=s=>document.querySelector(s);
const S={token:new URLSearchParams(location.hash.slice(1)).get('token')??sessionStorage.getItem('pcap-token')??'',job:'',view:'Overview',after:'0',history:[],selected:null,status:null,report:null,rows:[],catalog:null};
if(S.token){sessionStorage.setItem('pcap-token',S.token);history.replaceState(null,'',location.pathname);}
function el(tag,attrs={},...children){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')n.className=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2).toLowerCase(),v);else if(k==='text')n.textContent=v;else if(v!==null&&v!==false)n.setAttribute(k,v===true?'':v);}for(const c of children.flat()){if(c!==null&&c!==undefined)n.append(c instanceof Node?c:document.createTextNode(String(c)));}return n;}
const button=(name,fn,attrs={})=>el('button',{...attrs,onClick:()=>safe(fn)},name);
function notice(text,error=false){$('#notice').textContent=text;$('#notice').classList.toggle('error',error);}
async function safe(fn){try{return await fn();}catch(e){notice(e.message??String(e),true);}}
async function api(path,data={},post=false,blob=false){let url='/api/'+path;const init={headers:{Authorization:'Bearer '+S.token}};if(post){init.method='POST';init.headers['Content-Type']='application/json';init.body=JSON.stringify(data);}else{url+='?'+new URLSearchParams(data);}const response=await fetch(url,init);if(!response.ok){const err=await response.json();throw Error(err.error??response.statusText);}return blob?response.blob():response.json();}
const nav=[['Overview','◈'],['Packets & events','▤'],['Flows & sessions','⇄'],['Protocols','◇'],['Transactions','⇌'],['Timeline','▥'],['Issues','⚑'],['Research','⌕'],['Case catalog','▧']];
for(const[name,icon]of nav)$('#nav').append(button([el('span',{},icon),name],async()=>{S.view=name;S.after='0';S.history=[];await render();},{'data-view':name}));
function panel(title,subtitle=''){return el('div',{class:'panel-heading'},el('h2',{},title),el('span',{},subtitle));}
function badge(state){return el('span',{class:'badge '+(STATES.includes(state)?state:'candidate')},state);}
function facts(data){const n=el('dl',{class:'facts'});for(const[k,v]of Object.entries(data))n.append(el('dt',{},k),el('dd',{},v??'Unknown'));return n;}
function stat(label,value,sub){return el('div',{class:'stat'},el('span',{},label),el('strong',{},value),el('small',{},sub));}
function jsonPreview(value){const full=JSON.stringify(value,null,2);return el('pre',{class:'json'},full.length>20000?full.slice(0,20000)+'\n… Preview limited to 20,000 characters; original structured record remains in the workspace.':full);}
async function refreshJobs(){const data=await api('jobs');const select=$('#jobs');select.replaceChildren(el('option',{value:''},'Choose workspace'));for(const j of data.jobs)select.append(el('option',{value:j.id},`${j.source_name} · ${j.state}`));select.value=S.job;}
async function poll(){if(!S.job)return;const status=await api('status',{job:S.job});S.status=status;$('#binding').textContent=status.source_binding==='bytes_and_spans_checked'?'Source bytes checked':'Provisional / incomplete';$('#binding').className='badge '+(status.state==='complete'?'observed':'incomplete');$('#run-label').textContent=`${status.mode==='rust'?'Independent Rust engine':'Container-only reference inspection'} · ${status.state}`;$('#cancel').disabled=!['running','queued'].includes(status.state);$('#footer-source').textContent=`${status.source_name} · run ${S.job.slice(0,12)} · ${status.mode}`;$('#stats').replaceChildren(stat('Packets',count(status.packets),'Source packet ordinals'),stat('Evidence events',count(status.events),'Incremental indexed observations'),stat('Source size',count(status.source_bytes)+' B','Original capture remains read-only'),stat('Run status',status.state,status.semantic_replay_verified?'Semantic replay verified':'Semantic replay not asserted'));}
async function render(){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===S.view));$('#title').textContent=S.view;const main=$('#main');main.replaceChildren();if(S.view==='Case catalog'){await catalog(main);return;}if(!S.job){main.append(panel('Begin an investigation','OFFLINE • LOCAL'),el('p',{class:'empty'},'Open a capture to explore indexed observations, inspect exact source bytes, or compare independently attributed parser interpretations. Build the Rust product for protocol analysis; container-only inspection is available without it.'),el('div',{class:'provenance-path'},el('b',{},'Immutable capture'),'→','Packets','→','Reconstruction','→','Messages','→','Transactions'));return;}
 await poll();if(S.view==='Overview'){await overview(main);return;}if(S.view==='Research'){await research(main);return;}if(S.view==='Timeline'){await timeline(main);return;}await eventTable(main);}
async function overview(main){main.append(panel('Capture identity & coverage','SOURCE BINDING ≠ AUTHENTICITY'));let summary;try{summary=await api('overview',{job:S.job});}catch(error){if(['queued','running'].includes(S.status.state)){main.append(el('p',{class:'empty'},'The isolated worker is opening the capture. Indexed results will appear as they are committed.'));return;}throw error;}main.append(el('div',{class:'panel-body'},facts({'Capture':S.status.source_name,'Source SHA-256':S.status.source_sha256??'Pending successful EOF','First exact timestamp':timestamp(summary.first_ns),'Last exact timestamp':timestamp(summary.last_ns),'Analysis scope':S.status.mode==='rust'?'Bounded windows; no unlimited TCP history claim':'Container framing, bytes and clocks only','Replay verification':'Not performed by this GUI session'})));
const grid=el('div',{class:'mini-grid panel-body'});for(const[title,values]of [['Evidence states',summary.states],['Protocol observations',summary.protocols]]){const section=el('section',{},el('h3',{},title));for(const[k,v]of Object.entries(values))section.append(el('div',{class:'metric-row'},badge(k),count(v)));if(!Object.keys(values).length)section.append(el('small',{},'No decoded protocol observations in this mode/run.'));grid.append(section);}main.append(grid,el('div',{class:'warning panel-body'},'A source hash identifies bytes. It does not prove who captured them, that a parser is correct, or that an attack occurred. Coverage cuts and competing interpretations remain part of the evidence.'));
}
function currentFilters(){return {...(S.filters??{}),job:S.job,after:S.after,limit:200};}
async function eventTable(main){const kindByView={'Flows & sessions':'flow.start','Protocols':'protocol.detection','Transactions':'transaction.candidate'};
S.filters={kind:kindByView[S.view]??'',...(S.savedFilters?.[S.view]??{})};const filters=el('div',{class:'filterbar'});const kind=el('input',{value:S.filters.kind,placeholder:'event kind','aria-label':'Event kind'}),protocol=el('input',{value:S.filters.protocol??'',placeholder:'protocol','aria-label':'Protocol'}),frame=el('input',{value:S.filters.frame??'',placeholder:'frame','aria-label':'Frame'}),state=el('select',{'aria-label':'Evidence state'},el('option',{value:''},'Every state'),...STATES.map(s=>el('option',{value:s},s)));state.value=S.filters.status??(S.view==='Issues'?'incomplete':'');
filters.append(kind,protocol,frame,state,button('Apply',async()=>{S.savedFilters??={};S.savedFilters[S.view]={kind:kind.value,protocol:protocol.value,frame:frame.value,status:state.value};S.after='0';S.history=[];await render();}));main.append(panel(S.view,'KEYSET PAGINATION • VIRTUALIZED ROWS'),filters);
S.filters.status=state.value;const data=await api('query',currentFilters());S.rows=data.rows;
const scroll=el('div',{class:'grid-scroll',tabindex:'0','aria-label':'Evidence observations'}),table=el('table',{class:'data-table'},el('thead',{},el('tr',{},...['ID','Observation','Evidence state','Protocol','Source / scope'].map(t=>el('th',{},t))))),body=el('tbody');table.append(body);scroll.append(table);main.append(scroll);
function draw(){const v=virtualRange(Math.max(0,scroll.scrollTop-36),scroll.clientHeight||430,S.rows.length);body.replaceChildren();const spacer=h=>{if(h>0){const td=el('td',{colspan:5});td.style.height=h+'px';td.style.padding='0';body.append(el('tr',{},td));}};spacer(v.top);for(const e of S.rows.slice(v.start,v.end)){const refs=packetRefs(e);const src=refs.length?'frame '+refs.map(r=>r.frame).slice(0,4).join(', '):e.session?'session '+e.session:'capture scope';const tr=el('tr',{'data-seq':e.sequence,tabindex:0,class:S.selected===e.sequence?'selected':'',onClick:()=>safe(()=>inspect(e.sequence)),onKeydown:event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();safe(()=>inspect(e.sequence));}}},el('td',{},e.sequence),el('td',{title:e.kind},e.kind),el('td',{},badge(e.status)),el('td',{},e.protocol??'—'),el('td',{title:src},src));body.append(tr);}spacer(v.bottom);}
scroll.addEventListener('scroll',draw,{passive:true});requestAnimationFrame(draw);
const previous=button('← Previous',async()=>{S.after=S.history.pop()??'0';await render();},{disabled:!S.history.length});const next=button('Next →',async()=>{S.history.push(S.after);S.after=data.next;await render();},{disabled:!data.has_more});main.append(el('div',{class:'pager'},el('span',{},`${data.rows.length} rows in this page · IDs kept as exact integers`),el('div',{},previous,next)));
if(!data.rows.length)main.append(el('p',{class:'empty'},S.status.mode==='container'?'This inspection mode has no stream, protocol, transaction or issue analysis. Use the Rust engine for those views.':'No indexed observations match this filter. Try another state or event kind.'));
}
async function inspect(sequence){S.selected=sequence;const d=await api('event',{job:S.job,sequence}),e=d.event;const n=$('#inspector');n.replaceChildren(panel('Evidence inspector','EVENT '+sequence));n.append(el('div',{class:'block'},badge(e.status),facts({'Kind':e.kind,'Protocol':e.protocol??'Unknown / not applicable','Session / window':e.session??'Not assigned','Stream range':e.stream_range?`${e.stream_range.start}…${e.stream_range.end}`:'Not applicable','Reconstructed hash':e.evidence.reconstructed_sha256??'No reconstructed bytes'})));
const relations=el('div',{class:'block'},el('h3',{},'Evidence relationships'));for(const[label,ids]of [['Inputs',d.parents],['Derived',d.children]]){relations.append(el('small',{},label+': '));for(const id of ids)relations.append(button('#'+id,()=>inspect(id),{class:'relation'}));if(!ids.length)relations.append(el('small',{},'none in this bounded query'));relations.append(el('br'));}if(d.truncated)relations.append(el('small',{},'Relationship preview reached its explicit limit.'));n.append(relations);
const refs=packetRefs(e);const source=el('div',{class:'block'},el('h3',{},'Original source bytes'));for(const r of refs.slice(0,16))source.append(button('Frame '+r.frame,()=>showHex(r.frame,e),{class:'relation'}));if(!refs.length)source.append(el('small',{},'No direct packet reference. Follow the related input events.'));n.append(source);const spans=el('details',{class:'block'},el('summary',{},`${d.spans.length} selected source spans`),jsonPreview(d.spans));n.append(spans,el('details',{class:'block'},el('summary',{},'Structured event (bounded preview)'),jsonPreview(e)));
if(refs.length)await showHex(refs[0].frame,e);document.querySelectorAll('tr[data-seq]').forEach(r=>r.classList.toggle('selected',r.dataset.seq===sequence));}
async function showHex(frame,event,start=0){const p=await api('packet',{job:S.job,frame,start,count:256});$('#hex-block')?.remove();const values=bytes(p.hex);const n=el('div',{class:'block',id:'hex-block'},el('h3',{},'Packet '+frame+' · hash checked'));n.append(el('small',{},`Source offset ${p.source_start} · ${p.captured_length} captured bytes`));const pre=el('div',{class:'hex'});const spans=(event?.evidence?.spans??[]).filter(s=>s.frame===frame);for(let i=0;i<values.length;i+=16){const row=el('div',{},(BigInt(start)+BigInt(i)).toString(16).padStart(8,'0')+'  ');for(let j=i;j<Math.min(i+16,values.length);j++){const absolute=BigInt(start+j);const selected=spans.some(s=>overlaps(absolute,absolute+1n,BigInt(s.packet_start),BigInt(s.packet_start)+BigInt(s.end)-BigInt(s.start)));row.append(el(selected?'mark':'span',{},values[j].toString(16).padStart(2,'0')+' '));}pre.append(row);}n.append(pre,el('div',{class:'row'},button('← Bytes',()=>showHex(frame,event,Math.max(0,start-256)),{disabled:start===0}),button('More bytes →',()=>showHex(frame,event,start+256),{disabled:BigInt(start+256)>=BigInt(p.captured_length)}),button('Derived from viewport',async()=>{const r=await api('reverse',{job:S.job,frame,start,end:Math.min(start+256,Number(p.captured_length))});const result=el('div',{},el('small',{},'Direct span-derived events: '));for(const e of r.rows)result.append(button('#'+e.sequence,()=>inspect(e.sequence),{class:'relation'}));if(!r.rows.length)result.append(el('small',{},'No direct source-span derivatives; packet references remain separate.'));n.append(result);})));$('#inspector').append(n);}
async function timeline(main){main.append(panel('Capture-time timeline','BOUNDED 10,000-PACKET PAGE'));const d=await api('timeline',{job:S.job});const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 720 230');svg.classList.add('chart');svg.setAttribute('role','img');svg.setAttribute('aria-label','Packet counts in exact capture-time buckets');const max=Math.max(1,...d.buckets.map(b=>b.count));for(let i=0;i<d.buckets.length;i++){const r=document.createElementNS(ns,'rect');r.setAttribute('x',String(20+i*680/d.buckets.length));r.setAttribute('y',String(200-170*d.buckets[i].count/max));r.setAttribute('width',String(Math.max(1,680/d.buckets.length-2)));r.setAttribute('height',String(170*d.buckets[i].count/max));const title=document.createElementNS(ns,'title');title.textContent=timestamp(d.buckets[i].start_ns)+': '+d.buckets[i].count+' packets';r.append(title);svg.append(r);}main.append(el('div',{class:'panel-body'},svg,facts({'Unknown timestamps':count(d.unknown),'Scope':d.scope,'More source packets':d.has_more?'Yes; this is not the complete capture histogram':'No additional packets in this query'})));}
async function research(main){main.append(panel('Parser differential research','ATTRIBUTED VIEWS · NEVER VOTING'));const controls=el('div',{class:'research-controls'},el('p',{class:'warning'},'Compare separately produced interpretations of the same immutable capture. The first visible disagreement is not automatically the first possible disagreement: missing adapter coverage remains explicit.'));
const row=el('div',{class:'row'});for(const[k,label]of [['container','Run independent container'],['product','Run Rust comparison'],['tshark','Run TShark']])row.append(button(label,async()=>{notice('Running bounded local comparison adapter.');const r=await api('research/run',{job:S.job,adapter:k},true);notice(r.status);await render();}));controls.append(row);
const importInput=el('input',{type:'file',accept:'.json','aria-label':'Import attributed interpretation'});importInput.addEventListener('change',()=>safe(async()=>{const file=importInput.files[0];if(!file)return;if(file.size>8*1024*1024)throw Error('Interpretation exceeds 8 MiB.');const value=JSON.parse(await file.text());await api('research/import',{job:S.job,interpretation:value},true);await render();}));controls.append(el('label',{},'Import separately attributed normalized JSON (not trusted)',importInput));
const data=await api('research/list',{job:S.job});const opts=()=>data.interpretations.filter(i=>i.producer).map(i=>el('option',{value:i.id},i.producer.id+' · '+i.producer.version+' · '+i.id.slice(0,6)));const left=el('select',{id:'left-view','aria-label':'Left interpretation'},...opts()),right=el('select',{id:'right-view','aria-label':'Right interpretation'},...opts());if(right.options.length>1)right.selectedIndex=1;controls.append(el('div',{class:'row'},el('label',{},'Interpretation A',left),el('label',{},'Interpretation B',right),button('Compare fields',async()=>{S.report=await api('research/compare',{job:S.job,left:left.value,right:right.value},true);drawReport(S.report);})));const results=el('div',{id:'comparison-results'});main.append(controls,results);
for(const i of data.interpretations.filter(i=>!i.producer))results.append(el('div',{class:'block'},badge(i.status),jsonPreview(i)));
function drawReport(report){results.replaceChildren();const first=report.first_semantic_divergence;const head=el('div',{class:'block'},el('h3',{},first?'First observed semantic divergence':'No differences within compared fields'));if(first){head.append(facts({'Layer':first.layer,'Anchor':first.key,'Field':first.field,'Earlier unresolved layers':first.earlier_unresolved_layers.join(', ')||'None declared','Earlier uncomparable observations':String(first.earlier_unresolved_observations?.length??'Not recorded by v1'),'Current layer fully covered':first.current_layer_coverage_complete===true?'Declared complete':first.current_layer_coverage_complete===false?'Partial / uncovered':'Not recorded by v1','Comparison claim':first.claim??'Legacy first-observed comparison','Correct implementation':'Unresolved — specification adjudication required'}));const frames=[...(first.left_evidence?.frames??[]),...(first.right_evidence?.frames??[])];if(frames.length)head.append(button('Jump to source witness',async()=>{const r=await api('query',{job:S.job,frame:frames[0],kind:'packet.observed',limit:1});if(r.rows.length)await inspect(r.rows[0].sequence);else notice('Packet is not yet indexed in this workspace.',true);}));}else head.append(el('p',{},'Agreement is not proof of correctness. Review all uncollected and non-comparable fields.'));results.append(head);
const scroll=el('div',{class:'case-list'}),t=el('table',{class:'compare-table'},el('thead',{},el('tr',{},...['Layer / field','Result','A','B'].map(v=>el('th',{},v))))),body=el('tbody');for(const row of report.rows.slice(0,500))body.append(el('tr',{class:row.result},el('td',{},row.layer+' '+row.key+' '+row.field),el('td',{},row.result),el('td',{},shortValue(row.left)),el('td',{},shortValue(row.right))));t.append(body);scroll.append(t);results.append(scroll);if(report.rows.length>500)results.append(el('p',{class:'block'},'Showing the first 500 fields. The full differential is retained in the export.'));
const acknowledge=el('input',{type:'checkbox',id:'raw-ack'});const exports=el('div',{class:'block'},el('label',{class:'row'},acknowledge,'Include original captured bytes in a local research ZIP. This may contain secrets.'));exports.append(button('Export adjudication bundle',async()=>{if(!acknowledge.checked)throw Error('Acknowledge the original-byte disclosure before export.');const result=await api('research/export',{job:S.job,left:left.value,right:right.value,include_raw_capture:true},true);const blob=await api('research/download',{job:S.job,name:result.name},false,true);const url=URL.createObjectURL(blob),a=el('a',{href:url,download:'pcap-research-'+result.name});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Research bundle saved locally. Adjudication remains unresolved.');}));results.append(exports);}
}
async function catalog(main){main.append(panel('Specification & adversarial case ledger','REGISTERED CASES ≠ QUALIFICATION'));const audit=await api('audit');main.append(el('div',{class:'panel-body'},el('p',{class:'warning'},`${audit.family_count} research subjects · ${audit.case_count} registered cases. Maintenance: ${audit.maintenance_status}. Qualification: ${audit.qualification_status}. No sustained fuzzing or all-family semantic correctness is implied.`)));const data=S.catalog??await api('catalog');S.catalog=data;const input=el('input',{placeholder:'Filter protocol, case or layer','aria-label':'Case filter'}),list=el('div',{class:'case-list'});const draw=()=>{list.replaceChildren();const q=input.value.toLowerCase();for(const c of data.cases.filter(c=>(c.id+' '+c.layer+' '+c.kind).toLowerCase().includes(q)).slice(0,200)){const row=el('div',{class:'case',tabindex:0},el('strong',{},c.id),el('span',{class:'badge'},c.kind),el('p',{},c.layer+' · '+c.rationale));const open=()=>{const n=$('#inspector');n.replaceChildren(panel('Research case',c.id),el('div',{class:'block'},jsonPreview(c)),el('div',{class:'block'},el('h3',{},'Specification references'),jsonPreview(c.specifications.map(id=>data.specifications[id]))));};row.addEventListener('click',open);row.addEventListener('keydown',e=>{if(e.key==='Enter')open();});list.append(row);}};input.addEventListener('input',draw);main.append(el('div',{class:'filterbar'},input),list);draw();}
$('#jobs').addEventListener('change',()=>safe(async()=>{S.job=$('#jobs').value;S.after='0';S.history=[];await render();}));
$('#start').addEventListener('click',()=>safe(async()=>{$('#start').disabled=true;try{const r=await api('start',{capture:$('#capture').value,mode:$('#mode').value,profile:$('#profile').value},true);S.job=r.id;S.view='Overview';S.after='0';S.history=[];await refreshJobs();notice(r.mode==='container'?'Container inspection only. No network, stream, protocol, or attack inference is performed.':'Rust analysis job started; observations remain provisional until complete source binding.');await render();}finally{$('#start').disabled=false;}}));
$('#cancel').addEventListener('click',()=>safe(async()=>{await api('cancel',{job:S.job},true);await render();}));
async function init(){if(!S.token){notice('Open the exact local URL printed by the launcher; its fragment contains the session token.',true);$('#start').disabled=true;return;}const c=await api('config');$('#mode').value=c.engine_available?'rust':'container';$('#mode option[value="rust"]').disabled=!c.engine_available;const captures=await api('captures');for(const f of captures.files)$('#captures').append(el('option',{value:f.path},count(f.bytes)+' bytes'));if(captures.files.length)$('#capture').value=captures.files[0].path;await refreshJobs();if(!c.engine_available)notice('Rust engine is not configured. Container-only inspection is available; build product and launch with --engine for protocol analysis.');await render();}
safe(init);setInterval(()=>{if(S.job&&['running','queued'].includes(S.status?.state))safe(async()=>{const before=S.status.state;await poll();if(before!==S.status.state)await render();});},1000);
